version: '3.9'

services:
  sqlserver:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    container_name: haircut_sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: